
ENV_NAME = 'Pendulum-v1'

ENV_DIR_NAME = ENV_NAME

BASE_POLICY_TRAIN_TIME_STEPS_INTERVAL = 500
BASE_POLICY_TRAIN_MAX_TOTAL_TIME_STEPS = 10000
BASE_POLICY_TRAIN_TOTAL_TIME_STEPS_ARRAY = range(0,
                                                 BASE_POLICY_TRAIN_MAX_TOTAL_TIME_STEPS+1,
                                                 BASE_POLICY_TRAIN_TIME_STEPS_INTERVAL)


DATA_DIR_NAME = 'Data'
FIGS_DIR_NAME = 'Figures'
BASE_POLICIES_DIR_NAME = 'BasePolicies'
MODEL_DIR_NAME = 'Models'
TRAJECTORIES_DIR_NAME = 'Trajectories'
PRIMORL_AGENT_DIR_NAME = 'PrimorlAgent'


PRIMORL_BATCH_SIZE = 16
PRIMORL_ENSEMBLE_SIZE = 5
PRIMORL_MODEL_MAX_TIME_STEPS = 500
PRIMORL_MODEL_NEURONS_PER_LAYER = 128
PRIMORL_MODEL_LEARNING_NUMBER_OF_EPOCHS = 20
PRIMORL_UNCERTAINTY_PENALTY = -1
PRIMORL_UNCERTAINTY_THRESHOLD = 1
PRIMORL_AGENT_LEARNING_TOTAL_TIME_STEPS = 10000
PRIMORL_SAMPLING_RATIO = 0.2
PRIMORL_NOISE_MULTIPLIER = 0.1
PRIMORL_NOISE_MULTIPLIER_LOW = 0.25
PRIMORL_NOISE_MULTIPLIER_HIGH = 0.45
PRIMORL_CLIPPING_NORM = 1.0



