
ENV_NAME = 'Pendulum-v1'

ENV_DIR_NAME = ENV_NAME

BASE_POLICY_TRAIN_TOTAL_TIME_STEPS = 10000

DATA_DIR_NAME = 'Data'
FIGS_DIR_NAME = 'Figures'
BASE_POLICIES_DIR_NAME = 'BasePolicies'
MODEL_DIR_NAME = 'Models'
TRAJECTORIES_DIR_NAME = 'Trajectories'
PRIMORL_AGENT_DIR_NAME = 'PrimorlAgent'


PRIMORL_BATCH_SIZE = 64
PRIMORL_ENSEMBLE_SIZE = 5
PRIMORL_MODEL_MAX_TIME_STEPS = 500
PRIMORL_MODEL_NEURONS_PER_LAYER = 128
PRIMORL_MODEL_NUMBER_OF_EPOCHS = 15
PRIMORL_UNCERTAINTY_PENALTY = -100
PRIMORL_AGENT_LEARNING_TOTAL_TIME_STEPS = 5000
